version: '3.5'
services:
#Services
 host:
  build:
    context: build
    args:
     ENVPATH: host.env
  entrypoint: ["bash", "-c", "exit"]
  networks:
   wan:
 router:
  build:
    context: build
    args:
     ENVPATH: router.env
  entrypoint: ["bash", "-c", "exit"]
  networks:
   wan:
networks:
  wan:
    driver: bridge
    driver_opts:
     com.docker.network.bridge.name: gns3_wan
    ipam:
     config:
       - subnet: 192.168.222.0/24
